### ISSUE TITLE
minilzo is licensed GPL

### ISSUE THREAD

**Issue by Taywee** [badboy/minilzo-rs#6]
minilzo is licensed under the terms of the GPL, meaning this crate is obligated to use the same license.

**Comment by badboy** [comment]
To the best of my knowledge no, I don't need to license it under GPL. I only need to have it GPL-compatible.
Consuming applications will also need to be GPL-compatible license.

**Comment by Taywee** [comment]
Anything that links to GPL software is required to be GPL.  I'm not certain that your code needs to be GPL, as you don't package the LZO code, but anything that uses it would need to be, unless they are using some alternate non-GPL implementation of the LZO API.

> Does the GPL have different requirements for statically vs dynamically linked modules with a covered work? (#GPLStaticVsDynamic)
> 
> No. Linking a GPL covered work statically or dynamically with other modules is making a combined work based on the GPL covered work. Thus, the terms and conditions of the GNU General Public License cover the whole combination. See also What legal issues come up if I use GPL-incompatible libraries with GPL software?

It is somewhat unclear if this is actually enforceable with dynamic linking, but the position of the GNU project is clear at least.  My primary concern is that consuming users might see your library's license and not know that they might be affected by the GPL from linking to LZO.

**Comment by skade** [comment]
This is incorrect. Everything that is distributed with GPL code linked in is not allowed to be distributed under a license that restricts the freedoms given by the GPL. This is different from what you describe.

The MIT does not restrict further then the GPL, so this mix is allowed.

**Comment by Taywee** [comment]
The GPL is restrictive and viral by design.  One of the primary intentions of the GPL is that linking to GPL code requires you to license your code GPL.  This is why LGPL and GPL with linking exceptions are necessary in other circumstances.

**Comment by Taywee** [comment]
After doing some research, I believe I was wrong on this.  GPL is concerned specifically with distribution, and linking doesn't matter until a linked binary/library is actually distributed, in which case the GPL applies.  I apologize for the bother.
